version: "3.8"
services:
  app:
      build: ./infra/php
      volumes:
        - ./vue-splash:/work

  web:
      build: ./infra/nginx
      ports:
        - 10080:80
      volumes:
        - ./vue-splash:/work
        - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  db-store: